### ISSUE TITLE
error in CSV-export (Cellmap pipeline)

### ISSUE THREAD

**Issue by SaibotMagd** [ClearAnatomics/ClearMap#21]
When I run the csv-export 
```
source = ws.source('cells');
  header = ', '.join([h[0] for h in source.dtype.names]);
  np.savetxt(ws.filename('cells', extension='csv'), source[:], header=header, delimiter=',')  

```  
I get the error:
```
source = ws.source('cells');
header = ', '.join([h[0] for h in source.dtype.names]);
np.savetxt(ws.filename('cells', extension='csv'), source[:], header=header, delimiter=',')  

Traceback (most recent call last):

  File "<ipython-input-15-d80deed88a15>", line 3, in <module>
    np.savetxt(ws.filename('cells', extension='csv'), source[:], header=header, delimiter=',')

  File "<__array_function__ internals>", line 6, in savetxt

  File "/home/user/anaconda3/envs/ClearMapStable/lib/python3.6/site-packages/numpy/lib/npyio.py", line 1451, in savetxt
    % (str(X.dtype), format))

TypeError: Mismatch between array dtype ('[('x', '<i8'), ('y', '<i8'), ('z', '<i8'), ('size', '<i8'), ('source', '<f8'), ('xt', '<f8'), ('yt', '<f8'), ('zt', '<f8'), ('order', '<i8'), ('name', 'S256')]') and format specifier ('%.18e,%.18e,%.18e,%.18e,%.18e,%.18e,%.18e,%.18e,%.18e,%.18e')
```

**Comment by SaibotMagd** [comment]
I probably solved it. The type-missmatch originate from the last value in the source-array:
```
print(source[0])
[(667, 1787, 0, 23, 28480., 125.88945269, 316.30610993, 21.2107557 , 0, b'universe')]
```
If you call a savetxt without a type parameter (fmt) you get the missmatch error because of the non-number value (%.18e = e or E : scientific notation with e or E). To solve it you can just overwrite the default save types for np.savetxt like:
```
source = ws.source('cells');
header = ', '.join([h[0] for h in source.dtype.names]);
fmt = '%.18e,%.18e,%.18e,%.18e,%.18e,%.18e,%.18e,%.18e,%.18e,%s';
np.savetxt(ws.filename('cells', extension='csv'), source[:], fmt=fmt, header=header, delimiter=',')  
```

**Comment by ChristophKirst** [comment]
Thanks for spotting this error. This is fixed in the new script in a slightly more elegant way !
