### ISSUE TITLE
Read-only file system: stitched.npy

### ISSUE THREAD

**Issue by ywang219** [ClearAnatomics/ClearMap#45]
Hi,

When I am running Cell detection: the following error occurred. i tried to change the permissions to read and write but it doesn't allow me. Has anybody come across with this issue? Thank you for your time!

OSError: [Errno 30] Read-only file system: '/home/riera/Documents/Brain4/stitched.npy'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/home/riera/ClearMap2/CellMap.py", line 198, in <module>
    processing_parameter=processing_parameter)

  File "/home/riera/ClearMap2/ClearMap/ImageProcessing/Experts/Cells.py", line 317, in detect_cells
    results, blocks = bp.process(detect_cells_block, source, sink=None, function_type='block', return_result=True, return_blocks=True, parameter=cell_detection_parameter, **processing_parameter)

  File "/home/riera/ClearMap2/ClearMap/ParallelProcessing/BlockProcessing.py", line 249, in process
    result  = [f.result() for f in futures];

  File "/home/riera/ClearMap2/ClearMap/ParallelProcessing/BlockProcessing.py", line 249, in <listcomp>
    result  = [f.result() for f in futures];

  File "/home/riera/anaconda3/envs/ClearMap/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()

  File "/home/riera/anaconda3/envs/ClearMap/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception

OSError: [Errno 30] Read-only file system: '/home/riera/Documents/Brain4/stitched.npy'

Original Traceback (most recent call last):
  File "/home/riera/ClearMap2/ClearMap/ParallelProcessing/ParallelTraceback.py", line 32, in wrapper
    return func(*args, **kwargs)
  File "/home/riera/ClearMap2/ClearMap/ParallelProcessing/BlockProcessing.py", line 338, in process_block_block
    result = function(*sources_and_sinks, **kwargs);
  File "/home/riera/ClearMap2/ClearMap/ImageProcessing/Experts/Cells.py", line 493, in detect_cells_block
    maxima = md.find_maxima(source.array, **parameter_maxima, verbose=verbose);
  File "/home/riera/ClearMap2/ClearMap/IO/Slice.py", line 331, in array
    return self.source.__getitem__(self.slicing);
  File "/home/riera/ClearMap2/ClearMap/IO/Source.py", line 442, in __getitem__
    return self.as_real().__getitem__(*args);
  File "/home/riera/ClearMap2/ClearMap/IO/MMP.py", line 152, in as_real
    return Source(location=self.location, shape=self.shape, dtype=self.dtype, order=self.order, name=self.name);
  File "/home/riera/ClearMap2/ClearMap/IO/MMP.py", line 42, in __init__
    memmap = _memmap(location=location, shape=shape, dtype=dtype, order=order, mode=mode, array=array);
  File "/home/riera/ClearMap2/ClearMap/IO/MMP.py", line 343, in _memmap
    array = np.lib.format.open_memmap(location);
  File "/home/riera/anaconda3/envs/ClearMap/lib/python3.7/site-packages/numpy/lib/format.py", line 872, in open_memmap
    mode=mode, offset=offset)
  File "/home/riera/anaconda3/envs/ClearMap/lib/python3.7/site-packages/numpy/core/memmap.py", line 225, in __new__
    f_ctx = open(os_fspath(filename), ('r' if mode == 'c' else mode)+'b')
OSError: [Errno 30] Read-only file system: '/home/riera/Documents/Brain4/stitched.npy'

**Comment by ChristophKirst** [comment]
This is a permission issue on your linux machine.

Make sure you can write files to the location given.

possible sources of error: you might be logged in as a different user or your disk quota is reached. This does not look like a ClearMap problem so i am closing it, but feel free to repopen.
