### ISSUE TITLE
divide by zero

### ISSUE THREAD

**Issue by dvanselow** [ClearAnatomics/ClearMap#71]
I've been trying to get binarization to run on one channel of a full dataset (3397, 8836, 5635), as .npy input while adjusting parameters for size_min, max overlap, axes and processes to allow my 64 thread, 256GB machine to run the TubeMap pipeline.

I've found settings that allows the script run under my memory requirement, but regardless of setting combinations, I cannot seem to get through binarization without erroring on what appears to be processing the last block with a divide by zero error:

`Original Traceback (most recent call last):
  File "/home/rec1/Desktop/workspace/lightsheet/ClearMap2-master/ClearMap/ParallelProcessing/ParallelTraceback.py", line 32, in wrapper
    return func(*args, **kwargs)
  File "/home/rec1/Desktop/workspace/lightsheet/ClearMap2-master/ClearMap/ParallelProcessing/BlockProcessing.py", line 338, in process_block_block
    result = function(*sources_and_sinks, **kwargs);
  File "/home/rec1/Desktop/workspace/lightsheet/ClearMap2-master/ClearMap/ImageProcessing/Experts/Vasculature.py", line 659, in binarize_block
    adaptive = threshold_adaptive(deconvolved, **parameter_adaptive)
  File "/home/rec1/Desktop/workspace/lightsheet/ClearMap2-master/ClearMap/ImageProcessing/Experts/Vasculature.py", line 973, in threshold_adaptive
    threshold = ls.apply_local_function(source, function=function, mask=mask, dtype=float, selem=selem, spacing=spacing, interpolate=interpolate, step = step);
  File "/home/rec1/Desktop/workspace/lightsheet/ClearMap2-master/ClearMap/ImageProcessing/LocalStatistics.py", line 142, in apply_local_function
    zoom = tuple(float(s) / float(r) for s,r in zip(shape, res_shape));
  File "/home/rec1/Desktop/workspace/lightsheet/ClearMap2-master/ClearMap/ImageProcessing/LocalStatistics.py", line 142, in <genexpr>
    zoom = tuple(float(s) / float(r) for s,r in zip(shape, res_shape));
ZeroDivisionError: float division by zero
`

Any ideas?

**Comment by dvanselow** [comment]
Block size was too small, I think there are filters passed at 30 x 30 and I was using block sizes of < 30!
