### ISSUE TITLE
ValueError: Cannot find name for type 'elastix_resampled_to_auto'!

### ISSUE THREAD

**Issue by smith6jt-cop** [ClearAnatomics/ClearMap#78]
Hello and thank you for sharing this great work.  I am trying to get up an running with ClearMap2 and get the following after what appears to be successful completion of the atlas registration step using our research computing resources:

Resampling: resampling axes (0, 1), slice (823,) / 824
Resampling: elapsed time: 0:05:20.725
Traceback (most recent call last):
  File "Start.py", line 56, in <module>
    "result_directory" :  ws.filename('elastix_resampled_to_auto')
  File "/blue/krauseeg/smith6jt/ClearMap/ClearMap2/ClearMap/IO/Workspace.py", line 286, in filename
    debug=debug, **kwargs);
  File "/blue/krauseeg/smith6jt/ClearMap/ClearMap2/ClearMap/IO/Workspace.py", line 152, in filename
    raise ValueError('Cannot find name for type %r!' % ftype);
ValueError: Cannot find name for type 'elastix_resampled_to_auto'!
/home/smith6jt/.conda/envs/ClearMap/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py:86: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
  warnings.warn("torch.distributed.reduce_op is deprecated, please use "
(ClearMap) smith6jt@c0900a-s17:ClearMap$ ^C
(ClearMap) smith6jt@c0900a-s17:ClearMap$ 

Here is the script I use to start:

#ClearMap path
import sys
sys.path.append('/blue/krauseeg/smith6jt/ClearMap/ClearMap2')

#load ClearMap modules
from ClearMap.Environment import *  #analysis:ignore

#directories and files
directory = '/blue/krauseeg/smith6jt/CMData'

expression_raw      = 'Signal.tif'
expression_auto     = 'Background.tif'

ws = wsp.Workspace('CellMap', directory=directory);
ws.update(raw=expression_raw, autofluorescence=expression_auto)
ws.debug = False

resources_directory = settings.resources_path

ws.info()

#init atals and reference files
annotation_file, reference_file, distance_file=ano.prepare_annotation_files(
    slicing=(slice(None),slice(None),slice(0,456)), orientation=(3,2,1),
    overwrite=False, verbose=True);

#alignment parameter files
align_channels_affine_file   = io.join(resources_directory, 'Alignment/align_affine.txt')
align_reference_affine_file  = io.join(resources_directory, 'Alignment/align_affine.txt')
align_reference_bspline_file = io.join(resources_directory, 'Alignment/align_bspline.txt')

resample_parameter_auto = {
    "source_resolution" : (12,37,12),
    "sink_resolution"   : (25,25,25),
    "processes" : None,
    "verbose" : True,
    };

res.resample(ws.filename('autofluorescence'),
             sink=ws.filename('resampled', postfix='autofluorescence'),
             **resample_parameter_auto)

#p3d.plot([ws.filename('resampled'), ws.filename('resampled', postfix='autofluorescence')])# Write your code here :-)

# align the two channels
align_channels_parameter = {
    #moving and reference images
    "moving_image" : ws.filename('resampled', postfix='autofluorescence'),
    "fixed_image"  : ws.filename('resampled'),

    #elastix parameter files for alignment
    "affine_parameter_file"  : align_channels_affine_file,
    "bspline_parameter_file" : None,

    #directory of the alig'/home/nicolas.renier/Documents/ClearMap_Ressources/Par0000affine.txt',nment result
    "result_directory" :  ws.filename('elastix_resampled_to_auto')
    };

elx.align(**align_channels_parameter);

# align autofluorescence to reference
align_reference_parameter = {
    #moving and reference images
    "moving_image" : reference_file,
    "fixed_image"  : ws.filename('resampled', postfix='autofluorescence'),

    #elastix parameter files for alignment
    "affine_parameter_file"  :  align_reference_affine_file,
    "bspline_parameter_file" :  align_reference_bspline_file,
    #directory of the alignment result
    "result_directory" :  ws.filename('elastix_auto_to_reference')
    };

elx.align(**align_reference_parameter);

I'm not sure if I did something wrong by starting with the script or if it's something else.  Any help would be greatly appreciated.

Thanks

**Comment by crousseau** [comment]
Hi,,

What you want is ws.filename('resampled_to_auto') not ws.filename('elastix_resampled_to_auto')
If you want you can now use the GUI and the new API
