### ISSUE TITLE
'import ClearMap.IO.IO' fails

### ISSUE THREAD

**Issue by slitvinov** [ClearAnatomics/ClearMap#9]
This commit 65b9b34dede4cf40a55fda17b1355e2bbd1edbc9 breaks an import of `IO.IO` due to cyclical dependencies.

```
lisergey@barry:~/org$ python3 -c 'import ClearMap.IO.IO'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/lisergey/org/ClearMap/IO/IO.py", line 33, in <module>
    import ClearMap.IO.MHD as mhd
  File "/home/lisergey/org/ClearMap/IO/MHD.py", line 20, in <module>
    import ClearMap.IO.IO as io
AttributeError: module 'ClearMap.IO' has no attribute 'IO'
```

**Comment by ChristophKirst** [comment]
Does this happen with the newest version too?
What pyhton version are you using?

**Comment by slitvinov** [comment]
This is what happens in the newest version:
```
lisergey@barry:~/org$ python3 -c 'import ClearMap.IO.IO'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/lisergey/org/ClearMap/IO/__init__.py", line 66, in <module>
    from ClearMap.IO.IO import *
  File "/home/lisergey/org/ClearMap/IO/IO.py", line 29, in <module>
    import ClearMap.IO.Source as src
  File "/home/lisergey/org/ClearMap/IO/Source.py", line 17, in <module>
    import ClearMap.IO.FileUtils as fu
AttributeError: module 'ClearMap' has no attribute 'IO'
```

```
lisergey@barry:~/org$ python3 --version
Python 3.6.9
```

```
lisergey@barry:~/org$ pip3 freeze
absl-py==0.9.0
apt-clone==0.2.1
apturl==0.5.2
asn1crypto==0.24.0
astor==0.8.1
astunparse==1.6.3
atari-py==0.2.6
attrs==19.3.0
Brlapi==0.6.6
cachetools==4.1.0
certifi==2018.1.18
cffi==1.14.0
chardet==3.0.4
click==7.1.2
cloudpickle==1.3.0
command-not-found==0.3
cryptography==2.1.4
cupshelpers==1.0
cycler==0.10.0
Cython==0.29
decorator==4.4.2
defer==1.0.6
dill==0.3.2
distro-info===0.18ubuntu0.18.04.1
fail2ban==0.10.2
freetype-py==2.1.0.post1
future==0.18.2
gast==0.2.2
glfw==1.11.2
glob2==0.7
google-auth==1.17.2
google-auth-oauthlib==0.4.1
google-pasta==0.2.0
grpcio==1.29.0
gym==0.17.2
h5py==2.10.0
httplib2==0.9.2
idna==2.6
imageio==2.8.0
importlib-metadata==1.6.1
joblib==0.15.1
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.2
keyring==10.6.0
keyrings.alt==3.0
kiwisolver==1.2.0
language-selector==0.1
launchpadlib==1.10.6
lazr.restfulclient==0.13.5
lazr.uri==1.0.3
lockfile==0.12.2
louis==3.5.0
macaroonbakery==1.1.3
Mako==1.0.7
Markdown==3.2.2
MarkupSafe==1.0
matplotlib==3.2.1
meld==3.18.0
more-itertools==8.4.0
mpi4py==3.0.3
natsort==7.0.1
netifaces==0.10.4
networkx==2.4
numpy==1.18.5
oauth==1.0.1
oauthlib==3.1.0
olefile==0.45.1
opencv-python==4.2.0.34
opt-einsum==3.2.1
packaging==20.4
PAM==0.4.2
pandas==1.0.4
pexpect==4.2.1
Pillow==5.1.0
pluggy==0.13.1
progressbar2==3.51.3
protobuf==3.12.2
py==1.8.2
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycairo==1.16.2
pycparser==2.20
pycrypto==2.6.1
pycups==1.9.73
pyglet==1.5.0
pygobject==3.26.1
PyICU==1.9.8
pymacaroons==0.13.0
PyNaCl==1.1.2
pyparsing==2.4.7
PyQt5==5.15.0
PyQt5-sip==12.8.0
pyqtgraph==0.11.0
pyRFC3339==1.0
pytest==5.4.3
python-apt==1.6.5+ubuntu0.3
python-dateutil==2.6.1
python-debian==0.1.32
python-utils==2.4.0
pytz==2018.3
PyWavelets==1.1.1
pyxdg==0.25
PyYAML==3.12
pyzmq==19.0.1
reportlab==3.4.0
requests==2.23.0
requests-oauthlib==1.3.0
requests-unixsocket==0.1.5
rsa==4.6
scikit-image==0.17.2
scipy==1.4.1
screen-resolution-extra==0.0.0
seaborn==0.10.1
SecretStorage==2.3.1
simplejson==3.13.2
six==1.15.0
ssh-import-id==5.7
stable-baselines==2.6.0
system-service==0.3
systemd-python==234
tensorboard==1.15.0
tensorboard-plugin-wit==1.6.0.post3
tensorflow==1.15.3
tensorflow-estimator==1.15.1
termcolor==1.1.0
tifffile==2020.6.3
torch==1.5.0
tqdm==4.46.1
ubuntu-drivers-common==0.0.0
ufw==0.36
unattended-upgrades==0.1
urllib3==1.22
usb-creator==0.3.3
vispy==0.6.4
wadllib==1.3.2
wcwidth==0.2.4
Werkzeug==1.0.1
wrapt==1.12.1
xkit==0.0.0
zipp==3.1.0
zmq==0.0.0
zope.interface==4.3.2
```

**Comment by slitvinov** [comment]
It does not work also with `Python 3.8.3`. This seems to be relevant
http://effbot.org/zone/import-confusion.htm

**Comment by ChristophKirst** [comment]
Thanks for the info. 

We use ClearMap in the anaconda environment provided in the new release and neither 
running python in the console nor through the IPython console on spyder produces this error.
Please try to run ClearMap in this way.

I get this error only the standard python environment on my linux system too.
The IO module has some intentionally designed 'circular' dependencies' that probably cause the trouble.
There is a way to fix this and we might look into this in the near future.

**Comment by ChristophKirst** [comment]
I just pushed a new version that does not produce the error in a standard python console.
Please try this version. If the issue still persist reopen it here !

thank you for your input!

**Comment by slitvinov** [comment]
Hm...I do not see new commits. The current version produces the error.
https://github.com/ChristophKirst/ClearMap2/commits/master

**Comment by ChristophKirst** [comment]
Sorry, my push did not go through, can you try again with the newest version.

**Comment by slitvinov** [comment]
No error. Thank you.
